# Generated by Django 5.2.17 on 2026-10-05 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_application_options_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'ordering': ['company_name']},
        ),
        migrations.RemoveField(
            model_name='employer',
            name='website',
        ),
        migrations.AddField(
            model_name='candidate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.JSONField(blank=True, default=list, help_text='e.g. [{"degree": "B.Tech CSE", "institution": "KTU", "year": 2025}]'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_salary',
            field=models.PositiveIntegerField(blank=True, help_text="Annual expected salary, in the platform's base currency.", null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_years',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employer',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-1000', '201-1000 employees'), ('1000+', '1000+ employees')], max_length=20),
        ),
        migrations.AddField(
            model_name='employer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='domain',
            field=models.CharField(blank=True, help_text='Company website domain, e.g. zecpath.com (used to sanity-check company emails).', max_length=255),
        ),
        migrations.AddField(
            model_name='employer',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employer',
            name='is_company_verified',
            field=models.BooleanField(default=False, help_text='Set by an admin once the company/domain is manually verified.'),
        ),
        migrations.AddField(
            model_name='employer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["Python", "Django"]'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
