# Generated by Django 5.2.17 on 2026-10-07 08:06

import app.resume_upload_path
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_employer_options_remove_employer_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_original_name',
            field=models.CharField(blank=True, help_text='The filename as the candidate uploaded it (for display only - never used on disk).', max_length=255),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_sha256',
            field=models.CharField(blank=True, help_text='Used to detect duplicate re-uploads.', max_length=64),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, upload_to=app.resume_upload_path.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
    ]
